### ISSUE TITLE
New property `handlerSchema` in `handlerDefinition` not in `provider.definition.schema.v1.json` 

### ISSUE THREAD

**Issue by ewbankkit** [aws-cloudformation/cloudformation-resource-schema#145]
Recent updates to some CloudFormation resource schemas

* AWS::NetworkManager::TransitGatewayRegistration
* AWS::NimbleStudio::LaunchProfile
* AWS::NimbleStudio::StreamingImage
* AWS::NimbleStudio::StudioComponent

have added a new property, `handlerSchema `, to certain `handlers`, e.g.

```json
    "list": {
      "handlerSchema": {
        "properties": {
          "GlobalNetworkId": {
            "$ref": "resource-schema.json#/properties/GlobalNetworkId"
          }
        },
        "required": ["GlobalNetworkId"]
      },
      "permissions": [
        "networkmanager:GetTransitGatewayRegistrations"
      ]
    },
```

This property has not been added to https://github.com/aws-cloudformation/cloudformation-resource-schema/blob/master/src/main/resources/schema/provider.definition.schema.v1.json, so validation of these resource schemas against the meta-schema are failing.

**Comment by kadrach** [comment]
https://github.com/aws-cloudformation/cloudformation-resource-schema/pull/147
